TRAIN:
  DATA_SOURCES: [disk]
  DATA_PATHS: [./data/train_images_0.npy]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: [./data/train_labels_0.npy]
  BATCH_SIZE: 32
  TRANSFORMS: [
      ["ssl_rotate", {"indices":[0]}],
      ["RandomResizedCrop", {"args": [224], "indices": [0]}],
      ["RandomHorizontalFlip"],
      ["ToTensor"],
      ["Normalize", {"args": [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]}],
  ]

TEST:
  DATA_SOURCES: [disk]
  DATA_PATHS: [./data/test_images.npy]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: [./data/test_labels.npy]
  BATCH_SIZE: 32
  TRANSFORMS: [
    ["ssl_rotate"],
    ["Resize", {"args": [256]}],
    ["CenterCrop", {"args": [224]}],
    ["ToTensor"],
    ["Normalize", {"args": [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]}],
  ]


MODEL:
  TRUNK:
    TYPE: "resnet50"
  HEAD:
    PARAMS: [["mlp", {"dims": [2048, 4]}]]
    APPLY_BATCHNORM: True
  FEATURE_EVAL_MODE: False
  EVAL_FEATURES: []

# Training Parameters
TRAINER:
  TRAIN_LOOP: "generic_train_loop"
  TRAIN_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  EVAL_LOOP: "generic_eval_loop"
  EVAL_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  MAX_EPOCHS: 90

OPTIMIZER:
  TYPE: "sgd"
  BASE_LR: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  DAMPENING: 0
  NESTEROV: False

SCHEDULER:
  TYPE: "step"
  STEP_SIZE: 30
  GAMMA: 0.1

CHECKPOINT:
  DIR: "./checkpoints"

VERBOSE: True
